### ISSUE TITLE
Boreas scheduler can not be deployed due to affinity/selector error

### ISSUE THREAD

**Issue by SaladBreaker** [torgeirl/boreas-scheduler#21]
Hello,

I was trying to deploy the boreas scheduler using:
```
kubectl apply -f deploymnets/scheduler.yaml 
```

After running the command the pod is stuck in pending:
```
NAME                                READY   STATUS    RESTARTS   AGE
boreas-scheduler-78d5df9fb8-bhjgs   0/2     Pending   0          34s

```

and the error message is the following
`kubectl describe pod/boreas-scheduler-78d5df9fb8-bhjgs -n kube-system`:
```
Name:           boreas-scheduler-78d5df9fb8-bhjgs
Namespace:      kube-system
Priority:       0
Node:           <none>
Labels:         component=scheduler
                pod-template-hash=78d5df9fb8
                tier=control-plane
                version=second
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/boreas-scheduler-78d5df9fb8
Containers:
  boreas-scheduler:
    Image:      ghcr.io/torgeirl/boreas-scheduler:latest
    Port:       <none>
    Host Port:  <none>
    Requests:
      cpu:        100m
    Liveness:     http-get http://:10251/health delay=15s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:10251/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8c2wx (ro)
  zephyrus2:
    Image:        jacopomauro/zephyrus2:v2.0.2
    Port:         <none>
    Host Port:    <none>
    Liveness:     http-get http://:9001/health delay=15s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:9001/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8c2wx (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-8c2wx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              node-role.kubernetes.io/control-plane=
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason             Age   From                Message
  ----     ------             ----  ----                -------
  Warning  FailedScheduling   59s   default-scheduler   0/5 nodes are available: 5 node(s) didn't match Pod's node affinity/selector. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling..
  Normal   NotTriggerScaleUp  51s   cluster-autoscaler  pod didn't trigger scale-up:

```

I left all the descriptions maybe it helps.

After removing from the scheduler.yml this part:
```
...
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
...
```

It works:
```
NAME                                READY   STATUS    RESTARTS   AGE
boreas-scheduler-57c8f6fdf7-l75vv   2/2     Running   0          2m22s
```

Does that part affect in any way the functionality of boreas?

**Comment by torgeirl** [comment]
Node selection for the `node-role.kubernetes.io/control-plane` label (combined with the adjacent `NoSchedule` toleration) allows Boreas to be scheduled on the cluster's master node, alongside the rest of Kubernetes' orchestration tools. It was introduced in v1.20 as a replacement for `node-role.kubernetes.io/master`, that got deprecation in v1.24. My guess it that you're either prevented from running custom services on the master node by your platform provider or you're testing with a cluster older than that v1.20.

> Does that part affect in any way the functionality of boreas?

Running on a worker node instead of the master node could effect its performance, the chance it gets distrupted by the Kubelet agent makes it less reliable, and for benchmarking it won't be comparable to the default scheduler so I would recommend running it on the master node. But it should run on a worker node if you like to test it there.

**Comment by SaladBreaker** [comment]
Hello, 

thanks for the quick response, I am using k8s 1.26.3. I see that without the field, it still got scheduled on the master node, but maybe it is just a coincidence. 

Now I have added the field to my deployments like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
...
spec:
  ...
  template:
    ...
    spec:
      schedulerName: boreas-scheduler
```

but all of them are stuck into pending, is this the right way to call the boreas-scheduler?

**Comment by torgeirl** [comment]
> is this the right way to call the boreas-scheduler?

Yes, that seems correct.

That is the default name (can be changed with the `BOREAS_SCHEDULER_NAME` environment variable). My guess is that there is an issue with [the service account and/or the cluster role binding](https://github.com/torgeirl/boreas-scheduler/blob/master/deployments/scheduler.yaml#L1-L18). If the role binding failed, the scheduling events will be rejected by the API server:

> **3.3.1 Deploying a custom scheduler**
> A critical part was a deployment configuration that granted scheduler privilege to the scheduler. Namespace bindings sent to the API server would otherwise be rejected as illegitimate, seemly originating from an unauthorized scheduler. Scheduling privilege was granted by adding a service account with such privilege in addition to the regular pod deployment, as demonstrated in listing 3.1. The service account is created in lines 1-5. It is granted the privilege on lines 15-18 through Kubernetes’ role-based access control (RBAC). The deployment of the Boreas scheduler itself starts on line 20.

You can see the scheduling events in Boreas' pod logs:
- `$ kubectl get pods --namespace=kube-system`
- `$ kubectl logs boreas-scheduler-<pod-identifier> boreas-scheduler --namespace=kube-system`

You will need to remove these before you re-deploy the the scheduler (see the provided ), so perhaps that wasn't done when you modified the node selector?

- `$ kubectl delete -f deployments/scheduler.yaml`
- `$ kubectl create -f deployments/scheduler.yaml`

**Comment by SaladBreaker** [comment]
I checked and the service account and the cluster role binding are created correctly. I looked at the logs of boreas and I see there is an error:
```
Defaulted container "boreas-scheduler" out of: boreas-scheduler, zephyrus2
Starting HTTP server on port 10251
Waiting for optimizer at port 9001 to get ready
...
Waiting for optimizer at port 9001 to get ready
Listning for scheduling events to process.
Traceback (most recent call last):
  File "/app/scheduler.py", line 162, in pod_requirements
    total_cpu += self.cpu_convertion(container.resources.requests['cpu'])
KeyError: 'cpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/scheduler.py", line 398, in <module>
    asyncio.run(scheduler.start(batch_limit=settings.getint('scheduler', 'BatchSize'),
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/scheduler.py", line 377, in start
    self.schedule_events(batch)
  File "/app/scheduler.py", line 321, in schedule_events
    spec['components'][set_nickname] = self.pod_requirements(set_events[0])
  File "/app/scheduler.py", line 165, in pod_requirements
    raise Exception('Resource request for {}\'s {} container lacks {} key.'.format(event['object'].metadata.name, container.name, e))
Exception: Resource request for balancer-7c9585b6dd-7s54g's balancer-container container lacks 'cpu' key.
```

Maybe you have seen this before?

Is this related to the fact that I only have requests for the memory and storage on the deployments?
```
      containers:
      - image: httpd
        name: balancer-container
        resources:
          requests:
            ephemeral-storage: 0.5Gi
            memory: 2048Mi
```

Thanks!
